name: Auto check

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Flutter CLI
      uses: steebchen/flutter@v1.0.0
    - name: Install dependencies
      run: flutter pub get
    - name: Run test publish
      run: flutter pub publish --dry-run
