name: Auto check

on: 
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Flutter action
      uses: subosito/flutter-action@v1.1.1
      #with:
        # The Flutter version to make available on the path
        # flutter-version: # optional
        # The Flutter build release channel
        # channel: # optional, default is stable
        # Deprecated. Use flutter-version instead. Will not be supported after October 1, 2019
        # version: # optional
    - name: Install dependencies
      run: flutter pub get
    - name: Run test publish
      run: flutter pub publish --dry-run
